### PR TITLE
fix log encoding detect

### PR DESCRIPTION
**Pull request by laolarou726**
## PR-Codex overview
This PR focuses on enhancing encoding handling, adding a new property to a model, and improving game version resolution helpers.

### Detailed summary
- Added `System.IO` import in `EncodingHelper.cs`
- Added `ClientVersion` property to `RawVersionModel`
- Improved encoding handling in `DefaultLogAnalyzer.cs`
- Added `TryGetMcVersionByClientVersion` method in `GameVersionHelper`
- Updated error handling in `GameResourcesResolveHelper`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by BiDuang — DISMISSED** [review]

**Comment by yueyinqiu** [comment]
I'm now wondering whether the `GuessEncoding` method could work as expected.

Won't decoding the string in UTF8 in advance break some things?

**Comment by yueyinqiu** [comment]
Meanwhile, is utf7 really used in some cases? If not, I recommend to remove the related codes, since `UTF7` is obsolete.

**Comment by laolarou726** [comment]
> I'm now wondering whether `GuessEncoding` method could work as expected.
> 
> Does it relies on BOM? And will decoding the string in UTF8 in advance break some things?

pretty sure its working

**Review by yueyinqiu — APPROVED** [review]
I'm forced to do that :(

**Pull request merged**
