### PR TITLE
fix concurrent issue

### PR DESCRIPTION
**Pull request by laolarou726**
## PR-Codex overview
The focus of this PR is to add thread safety to `DownloadHelper` and `DefaultLauncherProfileParser` and `DefaultLauncherAccountParser` classes.

### Detailed summary
- Added thread safety using locks to methods in `DefaultLauncherProfileParser` and `DefaultLauncherAccountParser`
- Removed `System.Buffers` import in `DownloadHelper.cs`
- Added `readonly object _lock` to classes for synchronization

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by yueyinqiu — DISMISSED** [review]
a ba a ba

**Review by yueyinqiu — APPROVED** [review]
wu b wu b

**Comment by BiDuang** [comment]
smpp

**Comment by yueyinqiu** [comment]
du l du l

**Comment by laolarou726** [comment]
smjb, stop spamming

**Pull request merged**
